permalink: /:title
url: http://blog.teamleada.com
destination: _deploy
pygments: true
lsi: false
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
